# frozen_string_literal: true

require_relative "shadwire/version"
require_relative "shadwire/errors"
require_relative "shadwire/binstub"
require_relative "shadwire/config"
require_relative "shadwire/project"
require_relative "shadwire/registry_client"
require_relative "shadwire/resolver"
require_relative "shadwire/installer"
require_relative "shadwire/dependencies"
require_relative "shadwire/differ"
require_relative "shadwire/ui"
require_relative "shadwire/commands/init"
require_relative "shadwire/commands/add"
require_relative "shadwire/commands/list"
require_relative "shadwire/commands/search"
require_relative "shadwire/commands/info"
require_relative "shadwire/commands/diff"
require_relative "shadwire/commands/update"
require_relative "shadwire/commands/remove"
require_relative "shadwire/commands/status"
require_relative "shadwire/cli"
